version: "3"

services:
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 8081:8081
    networks:
      - app-tier
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - 8080:8080
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
